# aadpodidentity.yaml
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: azure-identity-kv
spec:
  type: 0
  resourceID: /subscriptions/<YOUR_AZURE_SUBSCRIPTION_ID>/resourcegroups/rg-demo/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity-aks-kv
  clientID: "a0c038fd-3df3-4eaf-bb34-abdd4f78a0db" # ClientId of the created Identity ($ az identity create -g rg-demo -n identity-aks-kv)
